### ISSUE TITLE
unknown error: $ is not defined

### ISSUE THREAD

**Issue by kappakp88** [hyperia-sk/highlight-ception#1]
Running a cest file with seeElement

getting this error as soon as it hits the seeElement, when I remove the module the test runs successfully 
codeception v2.3.3

unknown error: $ is not defined

\vendor\facebook\webdriver\lib\remote\HttpCommandExecutor.php:320
\vendor\facebook\webdriver\lib\remote\RemoteWebDriver.php:535
\vendor\facebook\webdriver\lib\remote\RemoteWebDriver.php:296
\vendor\hyperia\highlight-ception\src\HighlightCeption.php:70
\vendor\hyperia\highlight-ception\src\HighlightCeption.php:142

**Comment by kappakp88** [comment]
turns out this is a local issue with the page I am on not having jquery

**Comment by kappakp88** [comment]
reopening issue, tested with simpleCept.php inside the test directory and got the same error, i fixed the error by replacing the $ with jQuery.

**Comment by arzzen** [comment]
Thanks for reporting @kpascal 

fixed in ad35f31da1c7e56a9a3658557e30ac356b8b4ee7, you can update last version
