### ISSUE TITLE
Highlight an Element and then try to click that same element 

### ISSUE THREAD

**Issue by kappakp88** [hyperia-sk/highlight-ception#4]
Codeception Version  = 2.3.5
HighlightCeption Version = 1.2.0

Running into an issue where I have text or an element get highlighted and then attempt to click the highlighted text causing codeception to fail because that text now has a span tag

```
Example:
$I->canSee("//td[contains(text(),'CC_20130130')]/..//a[text()='View Payments']");
$I->click("//td[contains(text(),'CC_20130130')]/..//a[text()='View Payments']");

There was 1 failure:

---------
1) PaymentFileRptCest: Payment file report functionality
 Test  tests\. . ...
 Step  Click "//td[contains(text(),'CC_20130130')]/..//a[text()='View Payments'] "
 Fail  CSS or XPath element with '//td[contains(text(),'CC_20130130')]/..//a[text()='View Payments'] ' was not found.
```

**Comment by nshelms** [comment]
Fundamental flaw in how we're highlighting text. I can think of two potential solutions.
1. Instead of highlighting the specific text, highlight the entire element instead.
2. Figure out a way to remove the span tag after a configurable wait time

@arzzen, what do you think?

**Comment by arzzen** [comment]
@nshelms I think the second solution is better.
It makes sense.

**Comment by nshelms** [comment]
Submitted fix in PR. See #5

**Comment by arzzen** [comment]
#5 Merged. Thanks for your contributions @nshelms @kpascal
